name: Build Installers

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant Gradle Permission
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Package App
        run: |
          jpackage \
          --input build/libs \
          --main-jar cortex.jar \
          --name Cortex \
          --dest dist \
          --type app-image

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: cortex-${{ runner.os }}
          path: dist/